version: '3.8'
services:
  frontend:
    build: ./docker/frontend
    container_name: vueapp
    ports:
      - '8080:8080'
    volumes:
      - ./frontend/app:/src
    stdin_open: true
    tty: true
  backend: 
    build: ./docker/backend
    container_name: goapp
    tty: true
    ports:
      - "8100:3000"
    volumes:
      - ./backend/app:/go/src/goapp
